import streamlit as st
from pypdf import PdfReader
import google.generativeai as genai
import os
import re
from fpdf import FPDF

# 1. Branding Settings
st.set_page_config(
    page_title="getshortlisted.online | AI Resume Analyzer", 
    page_icon="📄", 
    layout="centered"
)

# API Setup
my_key = os.environ.get("MY_API_KEY")
genai.configure(api_key=my_key)
model = genai.GenerativeModel('gemini-2.5-flash')

# 2. PDF Creation Function
def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 10, "ATS ANALYSIS REPORT", ln=True, align='C')
    pdf.line(10, 22, 200, 22)
    pdf.ln(10)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=11)
    clean_text = text.replace("**", "").replace("###", "").replace("##", "").replace("#", "").replace("*", "-")
    final_text = clean_text.encode('latin-1', 'ignore').decode('latin-1')
    pdf.multi_cell(0, 8, txt=final_text)
    
    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by getshortlisted.online", align='C')
    return pdf.output(dest='S').encode('latin-1')

# 3. UI Styles
st.markdown("""
<style>
.stButton>button {
    background: linear-gradient(90deg, #4CAF50, #00C9A7);
    color: white; border: none; border-radius: 12px; height: 3em; font-weight: bold; transition: 0.3s;
}
.stButton>button:hover { transform: scale(1.05); }
</style>
""", unsafe_allow_html=True)

# 4. Main App UI
st.title("📄 AI Resume Analyzer")
# --- 1. Inputs (Ab ye hamesha dikhenge) ---
uploaded_file = st.file_uploader("Upload Resume (PDF)", type=["pdf"], key="resume_input")
jd_text = st.text_area("Paste the Job Description (JD) here:", key="jd_input")

# --- 2. Buttons (Ab ye hamesha screen par rahenge) ---
col1, col2 = st.columns(2)

with col1:
    analyze = st.button("🚀 Analyze Resume", use_container_width=True)

with col2:
    clear = st.button("🧹 Clear All", use_container_width=True)

# --- 3. CLEAR LOGIC (SAB KUCH SAAF KARNE KE LIYE) ---
if clear:
    # Saare input fields ko reset karna
    st.session_state["jd_input"] = ""
    st.session_state["resume_input"] = None
    if "role_input" in st.session_state:
        st.session_state["role_input"] = ""
    
    # File uploader ko force reset karne ki trick
    if "resume_input" in st.session_state:
        st.session_state.pop("resume_input")
        
    st.rerun()

# --- 4. ANALYZE LOGIC (YE SIRF TAB CHALEGA JAB ANALYZE DABAYE) ---
if analyze:
    if uploaded_file:
        with st.spinner("Analyzing..."):
            # PDF se text nikalna
            resume_text = ""
            reader = PdfReader(uploaded_file)
            for page in reader.pages:
                resume_text += page.extract_text()
            
            # --- AI PROMPT & RESULT (Aapka purana wala code yahan se continue hoga) ---
            prompt = f"""
            Target Role: {target_job}
            JD: {jd_text}
            Resume: {resume_text}
            Give ATS Score, Strengths, Weaknesses, and Missing Keywords: (Comma-separated).
            """
            # ... baaki ka AI logic jo humne pehle set kiya tha ...
    else:
        # Agar bina file ke Analyze dabaya toh warning
        st.warning("Bhai, pehle Resume PDF upload toh karo!")

with st.sidebar:
    st.header("⚙️ Settings")
    target_job = st.text_input("🎯 Target Job Role", placeholder="e.g. Data Scientist", key="role_val")

# 5. Extraction & Logic
if uploaded_file:
    resume_text = ""
    reader = PdfReader(uploaded_file)
    for page in reader.pages:
        resume_text += page.extract_text()

    col1, col2 = st.columns(2)
    with col1:
        analyze = st.button("🚀 Analyze Resume", use_container_width=True)
    with col2:
        clear = st.button("🧹 Clear", use_container_width=True)

    if clear:
        # Saare widgets ki values reset karna
        st.session_state["resume_input"] = None
        st.session_state["jd_input"] = ""
        st.session_state["role_input"] = ""
        # Poori app ko refresh karna
        st.rerun()

    if analyze:
        with st.spinner("Analyzing..."):
            prompt = f"""
            Target Role: {target_job}
            JD: {jd_text}
            Resume: {resume_text}
            Give:
            1. ATS Score (out of 100)
            2. Strengths
            3. Weaknesses
            4. Missing Keywords: (Comma-separated list only)
            5. Improvements
            """
            response = model.generate_content(prompt)
            
            if response and response.text:
                full_text = response.text
                
                # Score Extraction
                score_match = re.search(r'(\d+)\s*/\s*100', full_text)
                score = int(score_match.group(1)) if score_match else 0
                
                st.subheader(f"📊 ATS Match Score: {score}%")
                st.progress(score / 100)

                # --- SICK SKILL TAGS ---
                if "Missing Keywords:" in full_text:
                    st.markdown("### 🎯 Skills to Add")
                    try:
                        raw_keywords = full_text.split("Missing Keywords:")[1].split("\n")[0]
                        keywords_list = [k.strip() for k in raw_keywords.split(",") if k.strip()]
                        tags = "".join([f'<span style="background-color:#1E3A8A;color:white;padding:5px 12px;border-radius:50px;margin:4px;display:inline-block;border:1px solid #3B82F6;font-size:12px;font-weight:bold;">{k}</span>' for k in keywords_list])
                        st.markdown(tags, unsafe_allow_html=True)
                        st.write("")
                    except: pass

                st.markdown("---")
                st.markdown(full_text)
                
                # Download
                pdf_bytes = create_pdf(full_text)
                st.download_button("📥 Download Report", data=pdf_bytes, file_name="Analysis.pdf", mime="application/pdf")