import streamlit as st
from pypdf import PdfReader
import google.generativeai as genai
import os
import re
from fpdf import FPDF
import docx2txt
import plotly.graph_objects as go

# 1. Branding Settings
st.set_page_config(
    page_title="getshortlisted.online | AI Resume Analyzer", 
    page_icon="📄", 
    layout="centered"
)

# Branding Title
st.title("📄 AI Resume Analyzer")
st.markdown("### Get your ATS score and improve your chances! 🚀")

# API Setup
my_key = os.environ.get("MY_API_KEY")
genai.configure(api_key=my_key)
model = genai.GenerativeModel('gemini-2.5-flash') 

# 1. Functions
def extract_text_from_docx(file):
    return docx2txt.process(file)

def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 10, "ATS ANALYSIS REPORT", ln=True, align='C')
    pdf.line(10, 22, 200, 22)
    pdf.ln(10)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=11)
    clean_text = text.replace("**", "").replace("###", "").replace("##", "").replace("#", "").replace("*", "-")
    pdf.multi_cell(0, 8, txt=clean_text.encode('latin-1', 'ignore').decode('latin-1'))
    
    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by getshortlisted.online", align='C')
    return pdf.output(dest='S').encode('latin-1')

# 2. UI Styles
st.markdown("""
<style>
.stButton>button {
    background: linear-gradient(90deg, #4CAF50, #00C9A7);
    color: white; border: none; border-radius: 12px; height: 3em; font-weight: bold; transition: 0.3s;
}
.stButton>button:hover { transform: scale(1.05); }
</style>
""", unsafe_allow_html=True)

# 3. Inputs
uploaded_file = st.file_uploader("Upload Resume (PDF or DOCX)", type=["pdf", "docx"], key="resume_input")
jd_text = st.text_area("Paste the Job Description (JD) here:", key="jd_input", height=200)

with st.sidebar:
    st.header("⚙️ Settings")
    target_job = st.text_input("🎯 Target Job Role", placeholder="e.g. Data Scientist", key="role_input")

# 4. Buttons Section
col_btn1, col_btn2 = st.columns(2)
with col_btn1:
    analyze = st.button("🚀 Analyze Resume", use_container_width=True)
with col_btn2:
    clear = st.button("🧹 Clear All", use_container_width=True)

# 5. Logic
if clear:
    for key in list(st.session_state.keys()):
        del st.session_state[key]
    st.rerun()

if analyze:
    if uploaded_file:
        with st.spinner("🔍 Deep Scanning Resume..."):
            try:
                # --- STEP 1: Text Extraction ---
                resume_text = ""
                file_extension = uploaded_file.name.split('.')[-1].lower()

                if file_extension == 'pdf':
                    reader = PdfReader(uploaded_file)
                    for page in reader.pages:
                        resume_text += page.extract_text()
                elif file_extension == 'docx':
                    resume_text = extract_text_from_docx(uploaded_file)
                
                context_jd = jd_text if jd_text.strip() else "Not provided. Analyze based on industry standards."

                # --- STEP 2: AI Prompt ---
                prompt = f"""
                Target Role: {target_job if target_job else 'Relevant Professional Role'}
                JD: {context_jd}
                Resume: {resume_text}
                
                Provide analysis and an OPTIMIZED RESUME in this EXACT format:
                - ATS Score: [score]/100
                - Technical Score: [0-100]
                - Experience Score: [0-100]
                - Education Score: [0-100]
                - Top 3 Recommended Roles: [Role 1, Role 2, Role 3]
                - Strengths: [list]
                - Weaknesses: [list]
                - Missing Keywords: [comma separated keywords]
                - Improvements: [steps]

                [OPTIMIZED_RESUME_START]
                (Rewrite the entire resume here naturally integrating missing keywords.)
                [OPTIMIZED_RESUME_END]
                """
                
                response = model.generate_content(prompt)
                
                if response and response.text:
                    full_text = response.text
                    
                    # Optimized Resume Extraction
                    optimized_resume = ""
                    display_report = full_text
                    if "[OPTIMIZED_RESUME_START]" in full_text:
                        parts = full_text.split("[OPTIMIZED_RESUME_START]")
                        display_report = parts[0]
                        optimized_resume = parts[1].split("[OPTIMIZED_RESUME_END]")[0].strip()

                    # Score Extraction
                    score_match = re.search(r'ATS Score: (\d+)', display_report)
                    score = int(score_match.group(1)) if score_match else 0
                    
                    # --- STEP 3: UI Display ---
                    st.subheader(f"📊 ATS Match Score: {score}%")
                    st.progress(score / 100)
                    st.markdown("---")
                    st.markdown(display_report)

                    # --- STEP 4: Download Buttons ---
                    col_dl1, col_dl2 = st.columns(2)
                    with col_dl1:
                        report_pdf = create_pdf(display_report)
                        st.download_button("📥 Download Analysis", data=report_pdf, file_name="ATS_Report.pdf", use_container_width=True)
                    
                    with col_dl2:
                        if optimized_resume:
                            opt_pdf = create_pdf(optimized_resume)
                            st.download_button("✨ Download Optimized Resume", data=opt_pdf, file_name="Optimized_Resume.pdf", use_container_width=True)

            except Exception as e:
                st.error(f"Error: {e}")
    else:
        st.warning("Bhai, kam se kam Resume toh upload karo!")