import streamlit as st
from pypdf import PdfReader
import google.generativeai as genai
import os
import re
from fpdf import FPDF

# 1. Branding Settings
st.set_page_config(
    page_title="getshortlisted.online | AI Resume Analyzer", 
    page_icon="📄", 
    layout="centered"
)

# API Setup
my_key = os.environ.get("MY_API_KEY")
genai.configure(api_key=my_key)
model = genai.GenerativeModel('gemini-2.5-flash') # Updated to latest stable

# 2. PDF Creation Function
def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 10, "ATS ANALYSIS REPORT", ln=True, align='C')
    pdf.line(10, 22, 200, 22)
    pdf.ln(10)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", size=11)
    clean_text = text.replace("**", "").replace("###", "").replace("##", "").replace("#", "").replace("*", "-")
    # Multi_cell handles long text
    pdf.multi_cell(0, 8, txt=clean_text.encode('latin-1', 'ignore').decode('latin-1'))
    
    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, "Generated by getshortlisted.online", align='C')
    return pdf.output(dest='S').encode('latin-1')

# 3. UI Styles
st.markdown("""
<style>
.stButton>button {
    background: linear-gradient(90deg, #4CAF50, #00C9A7);
    color: white; border: none; border-radius: 12px; height: 3em; font-weight: bold; transition: 0.3s;
}
.stButton>button:hover { transform: scale(1.05); }
</style>
""", unsafe_allow_html=True)

# 4. Main App UI
st.title("📄 AI Resume Analyzer")

# Inputs
uploaded_file = st.file_uploader("Upload Resume (PDF)", type=["pdf"], key="resume_input")
jd_text = st.text_area("Paste the Job Description (JD) here:", key="jd_input", height=200)

with st.sidebar:
    st.header("⚙️ Settings")
    target_job = st.text_input("🎯 Target Job Role", placeholder="e.g. Data Scientist", key="role_input")

# 5. Buttons Section (Variables always defined here)
col1, col2 = st.columns(2)

with col1:
    analyze = st.button("🚀 Analyze Resume", use_container_width=True)

with col2:
    # Yahan 'clear =' likhna zaroori hai!
    clear = st.button("🧹 Clear All", use_container_width=True)

# 6. Logic (Ab 'if clear' kaam karega)
if clear:
    for key in st.session_state.keys():
        del st.session_state[key]
    st.rerun()

if analyze:
    # Ab sirf Resume hona zaroori hai, JD optional hai
    if uploaded_file:
        with st.spinner("🔍 Analyzing..."):
            try:
                # 1. Extract Text
                resume_text = ""
                reader = PdfReader(uploaded_file)
                for page in reader.pages:
                    resume_text += page.extract_text()
                
                # 2. Dynamic Prompt (JD ke bina bhi chalega)
                # Agar jd_text khali hai toh hum AI ko bolenge general analysis kare
                context_jd = jd_text if jd_text.strip() else "Not provided. Analyze based on the Target Role only."

                prompt = f"""
                Target Role: {target_job if target_job else 'Relevant Professional Role'}
                JD: {context_jd}
                Resume: {resume_text}
                
                Provide analysis in this exact format:
                - ATS Score: [score]/100 (If JD is missing, score based on industry standards for the Target Role)
                - Strengths: [list]
                - Weaknesses: [list]
                - Missing Keywords: [comma separated keywords]
                - Improvements: [steps]
                """
                
                response = model.generate_content(prompt)
                
                if response and response.text:
                    full_text = response.text
                    
                    # --- BAAKI KA EXTRACTION LOGIC SAME RAHEGA ---
                    score_match = re.search(r'(\d+)\s*/\s*100', full_text)
                    score = int(score_match.group(1)) if score_match else 0
                    
                    st.subheader(f"📊 ATS Match Score: {score}%")
                    if not jd_text.strip():
                        st.info("ℹ️ Note: Ye score general industry standards par based hai kyunki JD provide nahi kiya gaya.")
                    
                    st.progress(score / 100)

                    # Skill Tags Logic
                    if "Missing Keywords:" in full_text:
                        st.markdown("### 🎯 Skills to Add")
                        raw_keywords = full_text.split("Missing Keywords:")[1].split("\n")[0]
                        keywords_list = [k.strip() for k in raw_keywords.split(",") if k.strip()]
                        tags = "".join([f'<span style="background-color:#1E3A8A;color:white;padding:5px 12px;border-radius:50px;margin:4px;display:inline-block;font-size:12px;">{k}</span>' for k in keywords_list])
                        st.markdown(tags, unsafe_allow_html=True)

                    st.markdown("---")
                    st.markdown(full_text)
                    
                    pdf_bytes = create_pdf(full_text)
                    st.download_button("📥 Download Report", data=pdf_bytes, file_name="ATS_Report.pdf", mime="application/pdf")
                
            except Exception as e:
                st.error(f"Error: {e}")
    else:
        # Ab warning sirf tab aayegi jab Resume hi na ho
        st.warning("Bhai, kam se kam Resume PDF toh upload karo!")